coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: codecov-sp
      paths:
        - codecov-sp-test/
      statuses:
        - type: project
          target: 100%
          threshold: 1%
    - name: codecov-mp
      paths:
        - codecov-mp-test/
      statuses:
        - type: project
          target: auto
          threshold: 1%
