name: Release component-1

on:
  pull_request:
    types: [closed]
    paths:
      - 'component-1/**' 

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: release
        run: ./component-1/gradlew release -Prelease.useAutomaticVersion=true
